gpt-4.1-nano:
  intelligence: ●●
  speed: ●●●●●
  type: chat
  model: gpt-4.1-nano
  input:
    image: true
  pricing:
    input: $0.10 / 1M tokens
    output: $0.40 / 1M tokens
  props: {}

gpt-4o-mini:
  intelligence: ●●
  speed: ●●●●
  type: chat
  model: gpt-4o-mini
  input:
    image: true
  pricing:
    input: $0.15 / 1M tokens
    output: $0.60 / 1M tokens
  props: {}